mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/align.jar -DgroupId=align -DartifactId=align -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/alignsvc.jar -DgroupId=alignsvc -DartifactId=alignsvc -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/apache-xml-xerces.jar -DgroupId=apache-xml-xerces -DartifactId=apache-xml-xerces -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/api.jar -DgroupId=api -DartifactId=api -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/arq.jar -DgroupId=arq -DartifactId=arq -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/blas-0.8.jar -DgroupId=blas-0.8 -DartifactId=blas-0.8 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/com.mysql.jdbc_5.1.5.jar -DgroupId=com.mysql.jdbc_5.1.5 -DartifactId=com.mysql.jdbc_5.1.5 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/commons-cli.jar -DgroupId=commons-cli -DartifactId=commons-cli -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/commons-codec-1.6.jar -DgroupId=commons-codec-1.6 -DartifactId=commons-codec-1.6 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/commons-csv-1.0.jar -DgroupId=commons-csv-1.0 -DartifactId=commons-csv-1.0 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/commons-fileupload.jar -DgroupId=commons-fileupload -DartifactId=commons-fileupload -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/commons-io.jar -DgroupId=commons-io -DartifactId=commons-io -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/commons-lang3-3.3.2.jar -DgroupId=commons-lang3-3.3.2 -DartifactId=commons-lang3-3.3.2 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/commons-lang3.jar -DgroupId=commons-lang3 -DartifactId=commons-lang3 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/dom4j-2.0.0-ALPHA-2.jar -DgroupId=dom4j-2.0.0-ALPHA-2 -DartifactId=dom4j-2.0.0-ALPHA-2 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/falcon.jar -DgroupId=falcon -DartifactId=falcon -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/gson.jar -DgroupId=gson -DartifactId=gson -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/hermit.jar -DgroupId=hermit -DartifactId=hermit -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/httpclient-4.2.6.jar -DgroupId=httpclient-4.2.6 -DartifactId=httpclient-4.2.6 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/httpclient-cache-4.2.6.jar -DgroupId=httpclient-cache-4.2.6 -DartifactId=httpclient-cache-4.2.6 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/httpclient.jar -DgroupId=httpclient -DartifactId=httpclient -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/httpcore-4.2.5.jar -DgroupId=httpcore-4.2.5 -DartifactId=httpcore-4.2.5 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/httpcore.jar -DgroupId=httpcore -DartifactId=httpcore -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/iddl.jar -DgroupId=iddl -DartifactId=iddl -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/iiop.jar -DgroupId=iiop -DartifactId=iiop -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/impl.jar -DgroupId=impl -DartifactId=impl -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/io.jar -DgroupId=io -DartifactId=io -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/iri.jar -DgroupId=iri -DartifactId=iri -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jackson-annotations-2.3.0.jar -DgroupId=jackson-annotations-2.3.0 -DartifactId=jackson-annotations-2.3.0 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jackson-core-2.3.3.jar -DgroupId=jackson-core-2.3.3 -DartifactId=jackson-core-2.3.3 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jackson-databind-2.3.3.jar -DgroupId=jackson-databind-2.3.3 -DartifactId=jackson-databind-2.3.3 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jade-http.jar -DgroupId=jade-http -DartifactId=jade-http -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jade.jar -DgroupId=jade -DartifactId=jade -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jcl-over-slf4j-1.7.6.jar -DgroupId=jcl-over-slf4j-1.7.6 -DartifactId=jcl-over-slf4j-1.7.6 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jcl-over-slf4j.jar -DgroupId=jcl-over-slf4j -DartifactId=jcl-over-slf4j -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jena-arq-2.13.0.jar -DgroupId=jena-arq-2.13.0 -DartifactId=jena-arq-2.13.0 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jena-core-2.13.0.jar -DgroupId=jena-core-2.13.0 -DartifactId=jena-core-2.13.0 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jena-iri-1.1.2.jar -DgroupId=jena-iri-1.1.2 -DartifactId=jena-iri-1.1.2 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jena-tdb-1.1.2.jar -DgroupId=jena-tdb-1.1.2 -DartifactId=jena-tdb-1.1.2 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jena.jar -DgroupId=jena -DartifactId=jena -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jetty-http.jar -DgroupId=jetty-http -DartifactId=jetty-http -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jetty-io.jar -DgroupId=jetty-io -DartifactId=jetty-io -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jetty-server.jar -DgroupId=jetty-server -DartifactId=jetty-server -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jetty-util.jar -DgroupId=jetty-util -DartifactId=jetty-util -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jsonld-java-0.5.1.jar -DgroupId=jsonld-java-0.5.1 -DartifactId=jsonld-java-0.5.1 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/jwnl.jar -DgroupId=jwnl -DartifactId=jwnl -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/libthrift-0.9.2.jar -DgroupId=libthrift-0.9.2 -DartifactId=libthrift-0.9.2 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/log4j-1.2.17.jar -DgroupId=log4j-1.2.17 -DartifactId=log4j-1.2.17 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/log4j-over-slf4j.jar -DgroupId=log4j-over-slf4j -DartifactId=log4j-over-slf4j -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/mtj-0.9.11.jar -DgroupId=mtj-0.9.11 -DartifactId=mtj-0.9.11 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/mysql-connector-java.jar -DgroupId=mysql-connector-java -DartifactId=mysql-connector-java -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/netlib-java-0.9.3.jar -DgroupId=netlib-java-0.9.3 -DartifactId=netlib-java-0.9.3 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/ontmalizer-1.0.2.jar -DgroupId=ontmalizer-1.0.2 -DartifactId=ontmalizer-1.0.2 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/ontosim.jar -DgroupId=ontosim -DartifactId=ontosim -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/ontowrap.jar -DgroupId=ontowrap -DartifactId=ontowrap -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/osgi-core.jar -DgroupId=osgi-core -DartifactId=osgi-core -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/owlapi-bin.jar -DgroupId=owlapi-bin -DartifactId=owlapi-bin -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/oyster.jar -DgroupId=oyster -DartifactId=oyster -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/postgresql-jdbc4.jar -DgroupId=postgresql-jdbc4 -DartifactId=postgresql-jdbc4 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/procalign.jar -DgroupId=procalign -DartifactId=procalign -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/rdfapi.jar -DgroupId=rdfapi -DartifactId=rdfapi -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/rdfparser.jar -DgroupId=rdfparser -DartifactId=rdfparser -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/relaxngDatatype-1.0.jar -DgroupId=relaxngDatatype-1.0 -DartifactId=relaxngDatatype-1.0 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/resolver.jar -DgroupId=resolver -DartifactId=resolver -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/servlet-api.jar -DgroupId=servlet-api -DartifactId=servlet-api -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/skosapi.jar -DgroupId=skosapi -DartifactId=skosapi -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/slf4j-api-1.7.6.jar -DgroupId=slf4j-api-1.7.6 -DartifactId=slf4j-api-1.7.6 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/slf4j-api.jar -DgroupId=slf4j-api -DartifactId=slf4j-api -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/slf4j-log4j12-1.7.6.jar -DgroupId=slf4j-log4j12-1.7.6 -DartifactId=slf4j-log4j12-1.7.6 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/slf4j-simple-1.7.19.jar -DgroupId=slf4j-simple-1.7.19 -DartifactId=slf4j-simple-1.7.19 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/xercesImpl-2.11.0.jar -DgroupId=xercesImpl-2.11.0 -DartifactId=xercesImpl-2.11.0 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/xercesImpl.jar -DgroupId=xercesImpl -DartifactId=xercesImpl -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/xml-apis-1.4.01.jar -DgroupId=xml-apis-1.4.01 -DartifactId=xml-apis-1.4.01 -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/xml-apis.jar -DgroupId=xml-apis -DartifactId=xml-apis -Dversion=1 -Dpackaging=maven-plugin
mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=lib-ext/xsom-20110101-SNAPSHOT.jar -DgroupId=xsom-20110101-SNAPSHOT -DartifactId=xsom-20110101-SNAPSHOT -Dversion=1 -Dpackaging=maven-plugin
